/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetakipsistemi;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author X550V
 */
public class kullanıcıSil extends javax.swing.JFrame {

    String kullanıcıId;

    /**
     * Creates new form kullanıcıSil
     */
    public kullanıcıSil() throws HeadlessException {
        initComponents();
    }
    Connection con;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        silincekOlanId = new javax.swing.JTextField();
        sil = new javax.swing.JButton();

        jLabel1.setText("Kullanıcı Id :");

        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sil, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(silincekOlanId))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(silincekOlanId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(sil)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        try {
            // TODO add your handling code here:
            boolean varmı = false;
            String parola;
            String parola2 = null;
            int yanıt;
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Database", "enes", "123");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM KULLANICI");
            while (rs.next()) {
                if (rs.getString("KULLANICIID").equalsIgnoreCase(silincekOlanId.getText())) {
                    varmı = true;

                    parola2 = rs.getString("KULLANICIPAROLA");
                }
            }

            if (varmı) {
                parola = JOptionPane.showInputDialog("Lütfen Parolanızı Giriniz ...");
                if (parola.equalsIgnoreCase(parola2)) {
                    yanıt = JOptionPane.showConfirmDialog(rootPane, "Onaylıyormusunuz ?");
                    if (yanıt == JOptionPane.YES_OPTION) {
                        s.executeUpdate("delete from KULLANICI where KULLANICIID=" + "'"+silincekOlanId.getText()+"'");
                        
                        JOptionPane.showMessageDialog(rootPane, "Kullanıcı Başarıyla Silindi ...");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Hatalı Parola ...");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Hatalı Kullanıcı Id ...");
            }

        } catch (SQLException ex) {
            Logger.getLogger(kullanıcıSil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_silActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullanıcıSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullanıcıSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullanıcıSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullanıcıSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kullanıcıSil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sil;
    private javax.swing.JTextField silincekOlanId;
    // End of variables declaration//GEN-END:variables
}
