/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetakipsistemi;

import java.util.List;
import java.util.StringTokenizer;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;

/**
 *
 * @author X550V
 */
public class malzemeDegistir extends javax.swing.JFrame {

    String kullanıcıId;
    DefaultListModel dlm = new DefaultListModel();
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProjeTakipSistemiPU");

    /**
     * Creates new form malzemeDegistir
     */
    public malzemeDegistir() {
        initComponents();
    }

    public malzemeDegistir(String kullanıcıId) {
        initComponents();
        this.kullanıcıId = kullanıcıId;
        dlm.removeAllElements();
        EntityManager em = emf.createEntityManager();
        Query q1 = em.createQuery("select p from Proje p where p.kullaniciid='" + kullanıcıId + "'");
        Query q2 = em.createQuery("select m from Malzeme m");
        List<Malzeme> malzemeler = q2.getResultList();
        List<Proje> projeler = q1.getResultList();
        for (Proje proje : projeler) {
            for (Malzeme malzeme : malzemeler) {
                if (malzeme.getKullanilacagiprojekodu().equals(proje.getProjekodu())) {
                    dlm.addElement(malzeme.getKodu());
                }
            }
        }
        malzemeList.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nakliyeFiyatı = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        malzemeİsmi = new javax.swing.JTextField();
        miktar = new javax.swing.JTextField();
        birimCinsi = new javax.swing.JComboBox<>();
        birimFiyatı = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        malzemeList = new javax.swing.JList<>();
        degistir = new javax.swing.JButton();

        jLabel16.setText("Malzeme İsmi");

        jLabel17.setText("Miktar");

        jLabel18.setText("Birim Fiyatı");

        birimCinsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Adet", "Torba", "Paket" }));

        jLabel19.setText("Nakliye Fiyatı");

        jLabel1.setText("Malzemeler");

        malzemeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                malzemeListValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(malzemeList);

        degistir.setText("Değiştir");
        degistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degistirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(birimCinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(malzemeİsmi, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(140, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(degistir, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(birimFiyatı, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nakliyeFiyatı, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(malzemeİsmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birimCinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(birimFiyatı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nakliyeFiyatı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(degistir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void degistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degistirActionPerformed
        // TODO add your handling code here:
        EntityManager em = emf.createEntityManager();
        Query q1 = em.createQuery("select m from Malzeme m");
        List<Malzeme> malzemeler = q1.getResultList();
        for (Malzeme malzeme : malzemeler) {
            if (malzeme.getKodu().equals(malzemeList.getSelectedValue())) {
                malzeme.setBiRiMfiYat(this.birimFiyatı.getText());
                malzeme.setAdi(this.malzemeİsmi.getText());
                malzeme.setMiKtar(this.miktar.getText());
                malzeme.setNakliYefiYat(this.nakliyeFiyatı.getText());
                malzeme.setCiNsi((String) birimCinsi.getSelectedItem());
                em.getTransaction().begin();
                em.getTransaction().commit();
                em.close();

            }

            for (int k = 0; k < projeYönetim.dtm2.getRowCount(); k++) {
                if (projeYönetim.dtm2.getValueAt(k, 6).equals(malzemeList.getSelectedValue())) {
                    projeYönetim.dtm2.setValueAt(malzemeİsmi.getText(), k, 0);
                    projeYönetim.dtm2.setValueAt(this.nakliyeFiyatı.getText(), k, 4);
                    projeYönetim.dtm2.setValueAt(birimFiyatı.getText(), k, 3);
                    projeYönetim.dtm2.setValueAt(birimCinsi.getSelectedItem(), k, 2);
                    projeYönetim.dtm2.setValueAt(this.miktar.getText(), k, 1);

                }
            }

        }
    }//GEN-LAST:event_degistirActionPerformed

    private void malzemeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_malzemeListValueChanged
        // TODO add your handling code here:

        EntityManager em = emf.createEntityManager();
        Query q1 = em.createQuery("select m from Malzeme m");
        List<Malzeme> malzemeler = q1.getResultList();
        for (Malzeme malzeme : malzemeler) {
            if (malzeme.getKodu().equals(malzemeList.getSelectedValue())) {
                this.birimFiyatı.setText(malzeme.getBiRiMfiYat());
                this.malzemeİsmi.setText(malzeme.getAdi());
                this.nakliyeFiyatı.setText(malzeme.getNakliYefiYat());
                this.miktar.setText(malzeme.getMiKtar());
            }
        }

    }//GEN-LAST:event_malzemeListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(malzemeDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(malzemeDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(malzemeDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(malzemeDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new malzemeDegistir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> birimCinsi;
    private javax.swing.JTextField birimFiyatı;
    private javax.swing.JButton degistir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JList<String> malzemeList;
    private javax.swing.JTextField malzemeİsmi;
    private javax.swing.JTextField miktar;
    private javax.swing.JTextField nakliyeFiyatı;
    // End of variables declaration//GEN-END:variables
}
