/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetakipsistemi;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;

/**
 *
 * @author X550V
 */
public class projeGiris extends javax.swing.JFrame {

    /**
     * Creates new form projeTanım
     */
    Connection con;

    public projeGiris() {

        initComponents();

        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Database", "enes", "123");

        } catch (SQLException ex) {
            Logger.getLogger(projeGiris.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    boolean desenKontrol(String desenMetni, String icindeDesenArananMetin) {

        Pattern desen = Pattern.compile(desenMetni);
        Matcher arama = desen.matcher(icindeDesenArananMetin);
        return arama.find();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        kullanıcıId = new javax.swing.JTextField();
        kullanıcıParola = new javax.swing.JPasswordField();
        girisYap = new javax.swing.JButton();
        kullanıcıOlustur = new javax.swing.JButton();
        kullanıcıSil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel23.setText("Kullanıcı ID");

        jLabel24.setText("Kullanıcı Parola");

        girisYap.setText("Giriş Yap");
        girisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisYapActionPerformed(evt);
            }
        });

        kullanıcıOlustur.setText("Yeni Kullanıcı Oluştur");
        kullanıcıOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanıcıOlusturActionPerformed(evt);
            }
        });

        kullanıcıSil.setText("Kullanıcı Sil");
        kullanıcıSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanıcıSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kullanıcıParola, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kullanıcıId, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(kullanıcıOlustur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(girisYap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kullanıcıSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(kullanıcıId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(kullanıcıParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(kullanıcıOlustur)
                .addGap(18, 18, 18)
                .addComponent(girisYap)
                .addGap(18, 18, 18)
                .addComponent(kullanıcıSil)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisYapActionPerformed
        try {
            // TODO add your handling code here:

            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM KULLANICI");
            boolean varmı = true;
            boolean parolaDogrumu = false;

            while (rs.next()) {
                if (rs.getString(1).equalsIgnoreCase(kullanıcıId.getText())) {
                    varmı = false;
                }
                if (rs.getString(2).equalsIgnoreCase(kullanıcıParola.getText())) {
                    parolaDogrumu = true;
                }
            }

            if (varmı) {
                JOptionPane.showMessageDialog(this, "Böyle Bir Kullanıcı Yoktur", "UYARI", JOptionPane.ERROR_MESSAGE, null);
            } else {
                if (parolaDogrumu) {
                    projeTanım prjtnm = new projeTanım(kullanıcıId.getText());
                    prjtnm.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Girdiğiniz Parola Hatalı", "UYARI", JOptionPane.ERROR_MESSAGE, null);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(projeGiris.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_girisYapActionPerformed

    private void kullanıcıOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanıcıOlusturActionPerformed

        try {
            // TODO add your handling code here:

            Statement s = con.createStatement();
            boolean varmı = true;
            ResultSet rs = s.executeQuery("SELECT * FROM KULLANICI");
            if (kullanıcıId.getText().length() >= 5) {
                if (!desenKontrol("[^a-zA-Z0-9]", kullanıcıId.getText())) {
                    if (kullanıcıParola.getText().length() >= 5) {
                        if (!desenKontrol("[^a-zA-Z0-9]", kullanıcıParola.getText())) {
                            while (rs.next()) {
                                if (rs.getString("KULLANICIID").equalsIgnoreCase(kullanıcıId.getText())) {
                                    varmı = false;
                                }
                            }

                            if (varmı) {
                                projeTanım prjT = new projeTanım(kullanıcıId.getText());
                                prjT.setVisible(true);
                                s.executeUpdate("INSERT INTO KULLANICI (KULLANICIID,KULLANICIPAROLA)" + "VALUES('" + kullanıcıId.getText() + "'," + "'" + kullanıcıParola.getText() + "')");
                            } else {
                                JOptionPane.showMessageDialog(null, "Böyle Bir Kullanıcı Vardır", "UYARI", JOptionPane.ERROR_MESSAGE, null);

                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Parola Özel Karakter İçermemeli ...", "UYARI", JOptionPane.ERROR_MESSAGE, null);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Parola 5 Karakterden Uzun Olmalıdır ...", "UYARI", JOptionPane.ERROR_MESSAGE, null);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Kullanıcı Id Özel Karakter İçermemeli ...", "UYARI", JOptionPane.ERROR_MESSAGE, null);
                }
            } else {

                JOptionPane.showMessageDialog(null, "Kullanıcı Id 5 Karakterden Uzun Olmalıdır ...", "UYARI", JOptionPane.ERROR_MESSAGE, null);

            }
        } catch (SQLException ex) {
            Logger.getLogger(projeGiris.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kullanıcıOlusturActionPerformed

    private void kullanıcıSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanıcıSilActionPerformed
        // TODO add your handling code here:
        kullanıcıSil kllncSl = new kullanıcıSil();
        kllncSl.setVisible(true);

    }//GEN-LAST:event_kullanıcıSilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projeGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projeGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projeGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projeGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projeGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton girisYap;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JTextField kullanıcıId;
    private javax.swing.JButton kullanıcıOlustur;
    private javax.swing.JPasswordField kullanıcıParola;
    private javax.swing.JButton kullanıcıSil;
    // End of variables declaration//GEN-END:variables
}
