/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetakipsistemi;

import java.awt.HeadlessException;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author X550V
 */
public class projeAnaliz extends javax.swing.JFrame {

    String kullanıcıId;
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProjeTakipSistemiPU");

    /**
     * Creates new form projeAnaliz
     */
    public projeAnaliz(String kullanıcıId) {
        initComponents();
        projeKodları.removeAllItems();
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select p from Proje p where p.kullaniciid='" + kullanıcıId + "'");
        List<Proje> projeler = q.getResultList();
        this.kullanıcıId = kullanıcıId;
        for (Proje proje : projeler) {
            projeKodları.addItem(proje.getProjekodu());
        }

    }

    public projeAnaliz() throws HeadlessException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jtable = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personelTablosu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        MaliyetTablosu = new javax.swing.JTable();
        projeKodları = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        baslangıcGun = new javax.swing.JLabel();
        baslangıcAy = new javax.swing.JLabel();
        baslangıcYıl = new javax.swing.JLabel();
        bitisGun = new javax.swing.JLabel();
        bitisAy = new javax.swing.JLabel();
        bitisYıl = new javax.swing.JLabel();
        projeIsmi = new javax.swing.JLabel();
        projeninAmacı = new javax.swing.JLabel();
        maliyet = new javax.swing.JLabel();
        projeSatısBedeli = new javax.swing.JLabel();
        toplamKar = new javax.swing.JLabel();
        toplamPersonelMaası = new javax.swing.JLabel();
        personelMaasları = new javax.swing.JLabel();
        malzemeGideri = new javax.swing.JLabel();
        malzemeGiderii = new javax.swing.JLabel();
        nakliyeGideri = new javax.swing.JLabel();
        nakliyeGideriii = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jtable.setText("Toplam Kar                 :");

        jLabel25.setText("Proje İsmi                   :");

        jLabel33.setText("Maliyet                       :");

        jLabel26.setText("Proje Kodu                  :");

        jLabel27.setText("Başlangıç Tarihi           :");

        jLabel28.setText("Bitiş Tarihi                   :");

        jLabel34.setText("Genel Analiz");

        jLabel29.setText("Proje Satış Bedeli        :");

        personelTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Personel Adı", "Soyadı", "Özelliği", "Rütbesi", "GirişTarihi", "Çalışacağı Proje", "Tc Kimlik"
            }
        ));
        jScrollPane1.setViewportView(personelTablosu);

        MaliyetTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Malzeme İsmi", "Miktar", "Cinsi", "Birim Fiyatı", "Nakliye Fiyatı", "Proje", "Tarih"
            }
        ));
        jScrollPane2.setViewportView(MaliyetTablosu);

        projeKodları.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                projeKodlarıİtemStateChanged(evt);
            }
        });

        jLabel1.setText("Projenin Amacı           :");

        baslangıcGun.setText("jLabel2");

        baslangıcAy.setText("jLabel3");

        baslangıcYıl.setText("jLabel4");

        bitisGun.setText("jLabel5");

        bitisAy.setText("jLabel6");

        bitisYıl.setText("jLabel7");

        projeIsmi.setText("jLabel2");

        projeninAmacı.setText("jLabel2");

        maliyet.setText("jLabel2");

        projeSatısBedeli.setText("jLabel2");

        toplamKar.setText("jLabel2");

        toplamPersonelMaası.setText("Toplam Personel Maaşı:");

        personelMaasları.setText("jLabel3");

        malzemeGideri.setText("Toplam Malzeme Gideri");

        malzemeGiderii.setText("jLabel5");

        nakliyeGideri.setText("Toplam Nakliye Gideri  :");

        nakliyeGideriii.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(projeSatısBedeli, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(122, 122, 122))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bitisGun)
                                                    .addComponent(baslangıcGun))
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bitisAy, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                                    .addComponent(baslangıcAy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bitisYıl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(baslangıcYıl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(46, 46, 46))
                                            .addComponent(projeIsmi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(projeninAmacı, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(projeKodları, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtable)
                                            .addComponent(jLabel33)
                                            .addComponent(toplamPersonelMaası)
                                            .addComponent(malzemeGideri)
                                            .addComponent(nakliyeGideri)
                                            .addComponent(jLabel29))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(maliyet, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(personelMaasları)
                                        .addComponent(toplamKar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nakliyeGideriii)
                                        .addComponent(malzemeGiderii)))))
                        .addGap(47, 47, 47)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(projeKodları))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(projeIsmi)
                    .addComponent(jLabel33)
                    .addComponent(maliyet))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(baslangıcYıl)
                            .addComponent(baslangıcAy, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(projeSatısBedeli))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtable)
                                    .addComponent(toplamKar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(toplamPersonelMaası)
                                    .addComponent(personelMaasları))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nakliyeGideri)
                                    .addComponent(nakliyeGideriii))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(malzemeGiderii)
                                    .addComponent(malzemeGideri)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(projeninAmacı, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(baslangıcGun))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(bitisGun)
                                    .addComponent(bitisAy)
                                    .addComponent(bitisYıl))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projeKodlarıİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_projeKodlarıİtemStateChanged
        // TODO add your handling code here:
        dtm.getDataVector().removeAllElements();
        dtm2.getDataVector().removeAllElements();
        String[] basTarih, bitTarih;
        int toplamPersonelMaası = 0;
        int nakliyeGideri = 0, malzemeGideri = 0;
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select p from Proje p where p.kullaniciid='" + kullanıcıId + "'");
        Query q1 = em.createQuery("select p from Personel p");
        Query q2 = em.createQuery("select m from Malzeme m");
        List<Proje> projeler = q.getResultList();
        List<Personel> personeller = q1.getResultList();
        List<Malzeme> malzemeler = q2.getResultList();
        for (Malzeme malzeme : malzemeler) {
            if (malzeme.getKullanilacagiprojekodu().equals((String) projeKodları.getSelectedItem())) {
                nakliyeGideri += Integer.valueOf(malzeme.getNakliYefiYat());
                malzemeGideri += (Integer.valueOf(malzeme.getBiRiMfiYat()) * Integer.valueOf(malzeme.getMiKtar()));
            }
        }
        for (Proje proje : projeler) {
            if (proje.getProjekodu().equals((String) projeKodları.getSelectedItem())) {
                for (Personel personel : personeller) {
                    if (personel.getCalisacagiproje().equals((String) projeKodları.getSelectedItem())) {
                        String[] giris = personel.getGiristarih().split(",");
                        String[] bitis = proje.getBitistarih().split(",");
                        int yıl = Integer.valueOf(bitis[2]) - Integer.valueOf(giris[2]);
                        int ay = Integer.valueOf(bitis[1]) - Integer.valueOf(giris[1]);
                        toplamPersonelMaası += ((yıl * 12) * Integer.valueOf(personel.getMaas())) + ay * Integer.valueOf(personel.getMaas());
                    }
                }
            }
        }

        for (Proje proje : projeler) {
            if (proje.getProjekodu().equals((String) projeKodları.getSelectedItem())) {
                basTarih = proje.getBaslangictarih().split(",");
                bitTarih = proje.getBitistarih().split(",");
                projeIsmi.setText(proje.getProjeadi());
                baslangıcGun.setText(basTarih[0]);
                baslangıcAy.setText(basTarih[1]);
                baslangıcYıl.setText(basTarih[2]);
                bitisGun.setText(bitTarih[0]);
                bitisAy.setText(bitTarih[1]);
                bitisYıl.setText(bitTarih[2]);
                maliyet.setText(proje.getTahminiprojemaliyeti());
                toplamKar.setText(proje.getTahminiprojekari());
                projeninAmacı.setText(proje.getProjeninamaci());
                projeSatısBedeli.setText(proje.getProjesatisbedeli());
                personelMaasları.setText(String.valueOf(toplamPersonelMaası));
                this.malzemeGiderii.setText(String.valueOf(malzemeGideri));
                nakliyeGideriii.setText(String.valueOf(nakliyeGideri));
            }
        }

        dtm.setColumnIdentifiers(new String[]{"Personel Adı", "Soyadı", "Özelliği", "Rütbesi", "Tc Kimlik", "Giris Tarihi"});
        for (Personel personel : personeller) {
            if (personel.getCalisacagiproje().equals((String) projeKodları.getSelectedItem())) {
                dtm.addRow(new String[]{personel.getAdi(), personel.getSoyadi(), personel.getOzelligi(), personel.getRutbesi(), personel.getTckimlik(), personel.getGiristarih()});
            }
        }
        dtm2.setColumnIdentifiers(new String[]{"Malzeme Kodu", "Malzeme Ismi", "Türü", "Birim Fiyatı", "Nakliye Fiyatı", "Mıktar", "Alım Tarihi"});
        for (Malzeme malzeme : malzemeler) {
            if (malzeme.getKullanilacagiprojekodu().equals((String) projeKodları.getSelectedItem())) {
                dtm2.addRow(new String[]{malzeme.getKodu(), malzeme.getAdi(), malzeme.getCiNsi(), malzeme.getBiRiMfiYat(), malzeme.getNakliYefiYat(), malzeme.getMiKtar(), malzeme.getTariH()});
            }
        }
        personelTablosu.setModel(dtm);
        MaliyetTablosu.setModel(dtm2);

    }//GEN-LAST:event_projeKodlarıİtemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projeAnaliz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projeAnaliz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projeAnaliz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projeAnaliz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projeAnaliz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MaliyetTablosu;
    private javax.swing.JLabel baslangıcAy;
    private javax.swing.JLabel baslangıcGun;
    private javax.swing.JLabel baslangıcYıl;
    private javax.swing.JLabel bitisAy;
    private javax.swing.JLabel bitisGun;
    private javax.swing.JLabel bitisYıl;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jtable;
    private javax.swing.JLabel maliyet;
    private javax.swing.JLabel malzemeGideri;
    private javax.swing.JLabel malzemeGiderii;
    private javax.swing.JLabel nakliyeGideri;
    private javax.swing.JLabel nakliyeGideriii;
    private javax.swing.JLabel personelMaasları;
    private javax.swing.JTable personelTablosu;
    private javax.swing.JLabel projeIsmi;
    private javax.swing.JComboBox<String> projeKodları;
    private javax.swing.JLabel projeSatısBedeli;
    private javax.swing.JLabel projeninAmacı;
    private javax.swing.JLabel toplamKar;
    private javax.swing.JLabel toplamPersonelMaası;
    // End of variables declaration//GEN-END:variables
}
