/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetakipsistemi;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;

/**
 *
 * @author X550V
 */
public class projeOzellikDegistirme extends javax.swing.JFrame {

    DefaultListModel projeDegistirmeModel = new DefaultListModel();
    String kullanıcıId;

    /**
     * Creates new form projeOzellikDegistirme
     */
    Connection con;

    public projeOzellikDegistirme(DefaultListModel prjDgstrmMdl, String kullanıcıId) {
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Database", "enes", "123");
            initComponents();
            projeDegistirmeModel.removeAllElements();
            this.projeDegistirmeModel = prjDgstrmMdl;
            projeDegistirmeList.setModel(projeDegistirmeModel);
            this.kullanıcıId = kullanıcıId;
        } catch (SQLException ex) {
            Logger.getLogger(projeOzellikDegistirme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public projeOzellikDegistirme() throws HeadlessException {
        try {
            initComponents();
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Database", "enes", "123");
        } catch (SQLException ex) {
            Logger.getLogger(projeOzellikDegistirme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        projeDegistirmeList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        projeAdı = new javax.swing.JTextField();
        yapımcıFirma = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        projeninAmacı = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        projeSatısBedeli = new javax.swing.JTextField();
        tahminiProjeMaliyeti = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tahminiKarTutarı = new javax.swing.JTextField();
        degistir = new javax.swing.JButton();

        jLabel8.setText("Projeyi Seçiniz");

        projeDegistirmeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                projeDegistirmeListValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(projeDegistirmeList);

        jLabel5.setText("Projenin Amacı");

        jLabel7.setText("Projenin Adı");

        jLabel1.setText("Yapımcı Firma");

        jLabel10.setText("Proje Satış Bedeli");

        tahminiProjeMaliyeti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahminiProjeMaliyetiActionPerformed(evt);
            }
        });

        jLabel11.setText("Tahmini Proje Maliyeti");

        jLabel12.setText("Tahmini Kar Tutarı");

        degistir.setText("Değiştir");
        degistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degistirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yapımcıFirma, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(projeAdı)
                            .addComponent(tahminiProjeMaliyeti)
                            .addComponent(projeninAmacı))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addComponent(tahminiKarTutarı, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(projeSatısBedeli, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(degistir, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projeAdı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(projeSatısBedeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(yapımcıFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tahminiKarTutarı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(tahminiProjeMaliyeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projeninAmacı, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degistir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tahminiProjeMaliyetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahminiProjeMaliyetiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahminiProjeMaliyetiActionPerformed
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProjeTakipSistemiPU");
    private void degistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degistirActionPerformed

        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select p from Proje p where p.projekodu=" + projeDegistirmeList.getSelectedValue());

        List<Proje> liste = q.getResultList();
        //regex kontrollerini hallet.
        for (Proje proje : liste) {
            proje.setProjeadi(projeAdı.getText());
            proje.setProjeninamaci(projeninAmacı.getText());
            proje.setProjesatisbedeli(projeSatısBedeli.getText());
            proje.setTahminiprojekari(tahminiKarTutarı.getText());
            proje.setTahminiprojemaliyeti(tahminiProjeMaliyeti.getText());
            proje.setFirma(yapımcıFirma.getText());
        }
        em.getTransaction().begin();
        em.getTransaction().commit();
        em.close();

    }//GEN-LAST:event_degistirActionPerformed

    private void projeDegistirmeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_projeDegistirmeListValueChanged
        try {
            // TODO add your handling code here:
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM PROJE");
            while (rs.next()) {
                if (rs.getString("PROJEKODU").equalsIgnoreCase(projeDegistirmeList.getSelectedValue())) {
                    projeAdı.setText(rs.getString("PROJEKODU"));
                    yapımcıFirma.setText(rs.getString("FIRMA"));
                    tahminiProjeMaliyeti.setText(rs.getString("TAHMINIPROJEMALIYETI"));
                    projeninAmacı.setText(rs.getString("PROJENINAMACI"));
                    projeSatısBedeli.setText(rs.getString("PROJESATISBEDELI"));
                    tahminiKarTutarı.setText(rs.getString("TAHMINIPROJEKARI"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(projeOzellikDegistirme.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_projeDegistirmeListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projeOzellikDegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projeOzellikDegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projeOzellikDegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projeOzellikDegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projeOzellikDegistirme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton degistir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField projeAdı;
    private javax.swing.JList<String> projeDegistirmeList;
    private javax.swing.JTextField projeSatısBedeli;
    private javax.swing.JTextField projeninAmacı;
    private javax.swing.JTextField tahminiKarTutarı;
    private javax.swing.JTextField tahminiProjeMaliyeti;
    private javax.swing.JTextField yapımcıFirma;
    // End of variables declaration//GEN-END:variables
}
