/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetakipsistemi;

import java.awt.HeadlessException;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author X550V
 */
public class projeYönetim extends javax.swing.JFrame {

    public static DefaultTableModel dtm = new DefaultTableModel();
    public static DefaultTableModel dtm2 = new DefaultTableModel();
    DefaultComboBoxModel cbm = new DefaultComboBoxModel();
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProjeTakipSistemiPU");
    String kullanıcıId;
    Connection con;

    /**
     * Creates new form projeYönetim
     */
    public projeYönetim(String kullanıcıId) {
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Database", "enes", "123");
            initComponents();
            String tc;
            EntityManager em = emf.createEntityManager();
            this.kullanıcıId = kullanıcıId;
            dtm.getDataVector().removeAllElements();
            dtm.setColumnIdentifiers(new String[]{"Personel Adı", "Soyadı", "Özelliği", "Rütbesi", "Çalışacağı Proje", "Personel TC", "Giris Tarihi"});
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select * from PROJE");
            while (rs.next()) {
                if (rs.getString("KULLANICIID").equals(kullanıcıId)) {
                    cbm.addElement(rs.getString("PROJEKODU"));
                }
            }
            Query q = em.createQuery("select p from Personel p");
            Query q2 = em.createQuery("select p from Proje p");
            List<Personel> personeller = q.getResultList();
            List<Proje> projeler = q2.getResultList();
            for (Proje proje : projeler) {
                for (Personel personel : personeller) {
                    if (proje.getKullaniciid().equals(kullanıcıId)) {
                        if (proje.getProjekodu().equals(personel.getCalisacagiproje())) {
                            Personel a = new Personel();
                            tc = personel.getTckimlik();
                            a.setTckimlik(tc);
                            a.setCalisacagiproje(personel.getCalisacagiproje());
                            a.setMaas(personel.getMaas());
                            a.setCinsiyet(personel.getCinsiyet());
                            a.setAdi(personel.getAdi());
                            a.setOzelligi(personel.getOzelligi());
                            a.setRutbesi(personel.getRutbesi());
                            a.setSoyadi(personel.getSoyadi());
                            a.setGiristarih(personel.getGiristarih());
                            dtm.addRow(new String[]{a.getAdi(), a.getSoyadi(), a.getOzelligi(), a.getRutbesi(), a.getCalisacagiproje(), a.getTckimlik(), a.getGiristarih()});
                        }
                    }
                }
            }
            jComboBox2.setModel(cbm);
            jComboBox1.setModel(cbm);
            personelTablosu.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(projeYönetim.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public projeYönetim() throws HeadlessException {
        initComponents();
    }

    boolean desenKontrol(String desenMetni, String icindeDesenArananMetin) {

        Pattern desen = Pattern.compile(desenMetni);
        Matcher arama = desen.matcher(icindeDesenArananMetin);
        return arama.find();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        personelRutbesi = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        personelOzelligi = new javax.swing.JComboBox<>();
        personelAdı = new javax.swing.JTextField();
        personelSoyadı = new javax.swing.JTextField();
        personelMaas = new javax.swing.JTextField();
        personelEkle = new javax.swing.JButton();
        personelSil = new javax.swing.JButton();
        personelDegistir = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        personelTcNo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        personelKaydırma = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cinsiyetKadın = new javax.swing.JCheckBox();
        cinsiyetErkek = new javax.swing.JCheckBox();
        girisGun = new javax.swing.JComboBox<>();
        girisAy = new javax.swing.JComboBox<>();
        girisYıl = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        malzemeİsmi = new javax.swing.JTextField();
        miktar = new javax.swing.JTextField();
        birimCinsi = new javax.swing.JComboBox<>();
        birimFiyatı = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        nakliyeFiyatı = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        finansEkle = new javax.swing.JButton();
        malzemeDegistir = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        alısGun = new javax.swing.JComboBox<>();
        alısAy = new javax.swing.JComboBox<>();
        alısYıl = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        malzemeKodu = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        personelTablosu = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("Personel Adı");

        jLabel3.setText("Personel Soyadı");

        jLabel4.setText("Personel Rütbesi");

        jLabel13.setText("Personel Maaşı");

        personelRutbesi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Şef", "İşçi", "Usta", "Koordinatör", "Tekniker", "Şef Yardımcısı", "Teknisyen", "Mühendis" }));

        jLabel14.setText("Personel Özelliği");

        personelOzelligi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mimar", "İnşaat Mühendisi", "İşçi", "Elektrik Mühendisi" }));

        personelEkle.setText("Ekle");
        personelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelEkleActionPerformed(evt);
            }
        });

        personelSil.setText("Sil");
        personelSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelSilActionPerformed(evt);
            }
        });

        personelDegistir.setText("Değiştir");
        personelDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelDegistirActionPerformed(evt);
            }
        });

        jLabel21.setText("Personel Tc. Kimlik No");

        jLabel22.setText("İşe Giriş Tarihi");

        personelKaydırma.setText("Personel Kaydırma");
        personelKaydırma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                personelKaydırmaMouseExited(evt);
            }
        });
        personelKaydırma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelKaydırmaActionPerformed(evt);
            }
        });

        jLabel9.setText("Çalışacağı Proje Kodu");

        jLabel1.setText("Personel Cinsiyet");

        buttonGroup1.add(cinsiyetKadın);
        cinsiyetKadın.setText("Kadın");

        buttonGroup1.add(cinsiyetErkek);
        cinsiyetErkek.setText("Erkek");

        girisGun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        girisAy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylul", "Ekim", "Kasım", "Aralık" }));

        girisYıl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(102, 102, 102))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(80, 80, 80))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel22))
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(personelMaas, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(personelTcNo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(101, 101, 101)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(personelSil, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                            .addComponent(personelKaydırma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(personelOzelligi, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(cinsiyetErkek)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(personelAdı, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(personelSoyadı, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(personelRutbesi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(101, 101, 101)))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(personelEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(personelDegistir, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(117, 117, 117))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cinsiyetKadın)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(girisGun, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(girisAy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(girisYıl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(personelAdı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personelSoyadı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personelEkle)
                    .addComponent(jLabel3))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cinsiyetKadın)
                        .addGap(12, 12, 12)
                        .addComponent(personelDegistir)
                        .addGap(50, 50, 50)
                        .addComponent(personelSil)
                        .addGap(41, 41, 41)
                        .addComponent(personelKaydırma))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(cinsiyetErkek)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(personelRutbesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(personelOzelligi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(personelMaas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(personelTcNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(girisGun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(girisAy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(girisYıl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personel Yönetimi", jPanel5);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jLabel15.setText("Proje Kodu");

        jLabel16.setText("Malzeme İsmi");

        jLabel17.setText("Miktar");

        jLabel18.setText("Birim Fiyatı");

        birimCinsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Adet", "Torba", "Paket" }));

        jLabel19.setText("Nakliye Fiyatı");

        jLabel20.setText("Tarih");

        finansEkle.setText("Ekle");
        finansEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finansEkleActionPerformed(evt);
            }
        });

        malzemeDegistir.setText("Değiştir");
        malzemeDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malzemeDegistirActionPerformed(evt);
            }
        });

        jButton10.setText("İade");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        alısGun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        alısAy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylul", "Ekim", "Kasım", "Aralık" }));

        alısYıl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jLabel5.setText("Malzeme Kodu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(malzemeKodu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(malzemeİsmi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alısGun, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(alısAy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(alısYıl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(malzemeDegistir, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(birimCinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(birimFiyatı)
                            .addComponent(nakliyeFiyatı, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finansEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(finansEkle)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(malzemeKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(alısGun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alısAy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alısYıl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(malzemeİsmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(malzemeDegistir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birimCinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(birimFiyatı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nakliyeFiyatı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Finans Yönetimi", jPanel1);

        personelTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(personelTablosu);

        jButton1.setText("Proje Analiz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelEkleActionPerformed
        // TODO add your handling code here:
        EntityManager em = emf.createEntityManager();
        Query q1 = em.createQuery("select p from Proje p where p.kullaniciid='" + kullanıcıId + "'");
        Query q2 = em.createQuery("select p from Personel p");
        List<Personel> personeller = q2.getResultList();
        List<Proje> projeler = q1.getResultList();
        String cinsiyet;
        boolean varmı = true;
        boolean projeVarmı = false;
        boolean girisTarihiDogrumu = true;
        int[] girisTarih = new int[3];
        String girisTarihi = null;
        girisTarih[0] = (Integer.valueOf(girisGun.getSelectedIndex()) + 1);
        girisTarih[1] = (Integer.valueOf(girisAy.getSelectedIndex()) + 1);
        girisTarih[2] = (Integer.valueOf(girisYıl.getSelectedIndex()) + 2018);
        girisTarihi = girisTarih[0] + "," + girisTarih[1] + "," + girisTarih[2];
        for (Proje proje : projeler) {
            if (jComboBox1.getSelectedItem().equals(proje.getProjekodu())) {
                String bas[] = proje.getBaslangictarih().split(",");
                String bit[] = proje.getBitistarih().split(",");
                if (Integer.valueOf(bas[2]) > Integer.valueOf((String) girisYıl.getSelectedItem()) || Integer.valueOf(bit[2]) < Integer.valueOf((String) girisYıl.getSelectedItem())) {
                    girisTarihiDogrumu = false;
                }
            }
        }

        if (!desenKontrol("[^a-zA-Z]", personelAdı.getText())) {
            if (!desenKontrol("[^a-zA-Z]", personelSoyadı.getText())) {
                if (!desenKontrol("[^0-9]", personelMaas.getText())) {
                    for (Proje p : projeler) {
                        if (p.getProjekodu().equalsIgnoreCase((String) jComboBox1.getSelectedItem())) {
                            projeVarmı = true;
                        }
                    }

                    for (Personel p : personeller) {
                        if (p.getTckimlik().equalsIgnoreCase(this.personelTcNo.getText())) {
                            varmı = false;
                        }
                    }

                    if (!(personelAdı.getText().equalsIgnoreCase("") || personelMaas.getText().equalsIgnoreCase("") || (personelOzelligi.getSelectedIndex() == -1) || (personelRutbesi.getSelectedIndex() == -1) || personelSoyadı.getText().equalsIgnoreCase("") || personelTcNo.getText().equalsIgnoreCase("") || personelMaas.getText().equalsIgnoreCase(""))) {
                        if (personelTcNo.getText().length() == 11) {
                            if (projeVarmı) {
                                if (varmı) {
                                    if (girisTarihiDogrumu) {
                                        if (cinsiyetKadın.isSelected()) {
                                            cinsiyet = cinsiyetKadın.getText();
                                        } else {
                                            cinsiyet = cinsiyetErkek.getText();
                                        }

                                        File f = new File("C:/Users/X550V/Desktop", "Personel.dat");
                                        if (!f.exists()) {
                                            try {
                                                f.createNewFile();
                                            } catch (IOException ex) {
                                                Logger.getLogger(projeYönetim.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                        }
                                        try {
                                            Personel personel = new Personel(personelTcNo.getText(), personelAdı.getText(), personelSoyadı.getText(), personelOzelligi.getSelectedItem().toString(), personelRutbesi.getSelectedItem().toString(), (String) jComboBox1.getSelectedItem(), girisTarihi, personelMaas.getText(), cinsiyet);
                                            ObjectOutput oos = new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream("/C:/Users/X550V/Desktop/Personel.dat")));
                                            oos.writeObject(personel);
                                            oos.close();
                                        } catch (IOException ex) {
                                            Logger.getLogger(projeGiris.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                        Personel yeniPersonel = new Personel(personelTcNo.getText(), personelAdı.getText(), personelSoyadı.getText(), personelOzelligi.getSelectedItem().toString(), personelRutbesi.getSelectedItem().toString(), (String) jComboBox1.getSelectedItem(), girisTarihi, personelMaas.getText(), cinsiyet);
                                        em.getTransaction().begin();
                                        em.persist(yeniPersonel);
                                        em.getTransaction().commit();
                                        dtm.setColumnIdentifiers(new String[]{"Personel Adı", "Soyadı", "Özelliği", "Rütbesi", "Çalışacağı Proje", "Personel TC", "Giris Tarihi"});
                                        dtm.addRow(new String[]{yeniPersonel.getAdi(), yeniPersonel.getSoyadi(), yeniPersonel.getOzelligi(), yeniPersonel.getRutbesi(), yeniPersonel.getCalisacagiproje(), yeniPersonel.getTckimlik(), girisTarihi});
                                        personelTablosu.setModel(dtm);
                                        em.close();

                                    } else {
                                        JOptionPane.showMessageDialog(rootPane, "Tarihleri Kontrol Ediniz ...");
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(rootPane, "Bu Tc'ye Sahip Personelimiz Zaten Mevcuttur ...");
                                }
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Böyle Bir Proje Yoktur ...");
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "TC'yi Doğru Girdiğinizden Emin Olun ...");
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Bütün Değerleri Girdiğinizden Emin Olun ...");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Personel Maaşına Sadece Rakam Girdiğinizden Emin Olun ...");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Personel Soyadı Özel Karakter Ve Rakam İçeremez ...");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Personel Adı Özel Karakter Ve Rakam İçeremez ...");
        }
    }//GEN-LAST:event_personelEkleActionPerformed

    private void personelSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelSilActionPerformed
        try {
            // TODO add your handling code here:
            personelSil prsnlSl = new personelSil(kullanıcıId);
            prsnlSl.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(projeYönetim.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_personelSilActionPerformed

    private void personelDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelDegistirActionPerformed
        // TODO add your handling code here:
        personelOzellikDegistir dgstr = new personelOzellikDegistir(kullanıcıId);
        dgstr.setVisible(true);

    }//GEN-LAST:event_personelDegistirActionPerformed

    private void personelKaydırmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personelKaydırmaMouseExited
        // TODO add your handling code here:
        //yanlış bastım
    }//GEN-LAST:event_personelKaydırmaMouseExited

    private void personelKaydırmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelKaydırmaActionPerformed
        try {
            // TODO add your handling code here:
            personelKaydırma perKydrm = new personelKaydırma(kullanıcıId);
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select * from PROJE");
            while (rs.next()) {
                if (rs.getString("KULLANICIID").equals(kullanıcıId)) {
                    perKydrm.personelKaydırmaModel.addElement(rs.getString("PROJEKODU"));
                }
            }
            perKydrm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(projeYönetim.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_personelKaydırmaActionPerformed

    private void finansEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finansEkleActionPerformed
        // TODO add your handling code here:
        dtm2.getDataVector().removeAllElements();
        boolean malzemeVarmı = true;
        EntityManager em = emf.createEntityManager();

        String alısTarih;
        alısTarih = (alısGun.getSelectedIndex() + 1) + "," + (alısAy.getSelectedIndex() + 1) + "," + (alısYıl.getSelectedIndex() + 2018);
        Query q = em.createQuery("SELECT p FROM Proje p");
        List<Proje> projeler = q.getResultList();
        Query q2 = em.createQuery("select m from Malzeme m");
        List<Malzeme> malzemeler = q2.getResultList();

        for (Proje proje : projeler) {
            if (proje.getKullaniciid().equals(kullanıcıId)) {
                for (Malzeme malzeme : malzemeler) {
                    if (malzeme.getKullanilacagiprojekodu().equals(proje.getProjekodu())) {
                        dtm2.setColumnIdentifiers(new String[]{"Malzeme İsmi", "Miktar", "Türü", "Birim Fiyatı", "Nakliye Fiyatı", "Çalışacağı Proje", "Malzeme Kodu", "Tarih"});
                        dtm2.addRow(new String[]{malzeme.getAdi(), malzeme.getMiKtar(), malzeme.getCiNsi(), malzeme.getBiRiMfiYat(), malzeme.getNakliYefiYat(), malzeme.getKullanilacagiprojekodu(), malzeme.getKodu(), malzeme.getTariH()});
                    }
                }
            }
        }
        for (Proje proje : projeler) {
            if (proje.getKullaniciid().equals(kullanıcıId)) {
                for (Malzeme malzeme : malzemeler) {
                    if (malzeme.getKullanilacagiprojekodu().equals(proje.getProjekodu())) {
                        if (malzeme.getKodu().equals(malzemeKodu.getText())) {
                            malzemeVarmı = false;
                        }
                    }
                }
            }
        }
        if (!(malzemeKodu.getText().equals("") || miktar.getText().equals("") || malzemeİsmi.getText().equals("") || birimFiyatı.getText().equals("") || nakliyeFiyatı.getText().equals(""))) {
            if (malzemeVarmı) {
                if (!desenKontrol("[^0-9]", miktar.getText())) {
                    if (!desenKontrol("[^0-9]", birimFiyatı.getText())) {
                        if (!desenKontrol("[^0-9]", nakliyeFiyatı.getText())) {

                            Malzeme yeniMalzeme = new Malzeme(malzemeKodu.getText(), malzemeİsmi.getText(), (String) birimCinsi.getSelectedItem(), miktar.getText(), birimFiyatı.getText(), nakliyeFiyatı.getText(), alısTarih, (String) jComboBox2.getSelectedItem());
                            em.getTransaction().begin();
                            em.persist(yeniMalzeme);
                            em.getTransaction().commit();
                            dtm2.addRow(new String[]{yeniMalzeme.getAdi(), yeniMalzeme.getMiKtar(), yeniMalzeme.getCiNsi(), yeniMalzeme.getBiRiMfiYat(), yeniMalzeme.getNakliYefiYat(), yeniMalzeme.getKullanilacagiprojekodu(), yeniMalzeme.getKodu(), yeniMalzeme.getTariH()});
                            personelTablosu.setModel(dtm2);
                            JOptionPane.showMessageDialog(this, "Malzeme Oluşturuldu.");
                        } else {
                            JOptionPane.showMessageDialog(this, "Nakliye Fiyatına Sadece Rakam Girdiğinizden Emin Olun ...", "UYARI", JOptionPane.ERROR_MESSAGE, null);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Birim Fiyatına Sadece Rakam Girdiğinizden Emin Olun ...", "UYARI", JOptionPane.ERROR_MESSAGE, null);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Miktara Sadece Rakam Girdiğinizden Emin Olun ...", "UYARI", JOptionPane.ERROR_MESSAGE, null);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Bu Koda Sahip Malzeme Vardır ...", "UYARI", JOptionPane.ERROR_MESSAGE, null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bütün Alanları Doldurunuz ...", "UYARI", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_finansEkleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        projeAnaliz prjAnalz = new projeAnaliz(kullanıcıId);
        prjAnalz.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void malzemeDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malzemeDegistirActionPerformed
        // TODO add your handling code here:
        malzemeDegistir mlzmDgstr = new malzemeDegistir(kullanıcıId);
        mlzmDgstr.setVisible(true);
    }//GEN-LAST:event_malzemeDegistirActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        malzemeIade mlzmIade = new malzemeIade(kullanıcıId);
        mlzmIade.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseEntered

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projeYönetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projeYönetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projeYönetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projeYönetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projeYönetim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alısAy;
    private javax.swing.JComboBox<String> alısGun;
    private javax.swing.JComboBox<String> alısYıl;
    private javax.swing.JComboBox<String> birimCinsi;
    private javax.swing.JTextField birimFiyatı;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cinsiyetErkek;
    private javax.swing.JCheckBox cinsiyetKadın;
    private javax.swing.JButton finansEkle;
    private javax.swing.JComboBox<String> girisAy;
    private javax.swing.JComboBox<String> girisGun;
    private javax.swing.JComboBox<String> girisYıl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton malzemeDegistir;
    private javax.swing.JTextField malzemeKodu;
    private javax.swing.JTextField malzemeİsmi;
    private javax.swing.JTextField miktar;
    private javax.swing.JTextField nakliyeFiyatı;
    private javax.swing.JTextField personelAdı;
    private javax.swing.JButton personelDegistir;
    private javax.swing.JButton personelEkle;
    private javax.swing.JButton personelKaydırma;
    private javax.swing.JTextField personelMaas;
    private javax.swing.JComboBox<String> personelOzelligi;
    private javax.swing.JComboBox<String> personelRutbesi;
    private javax.swing.JButton personelSil;
    private javax.swing.JTextField personelSoyadı;
    private javax.swing.JTable personelTablosu;
    private javax.swing.JTextField personelTcNo;
    // End of variables declaration//GEN-END:variables
}
